Repository windingtree/homepage, pull requests merged in 2018-12, with the labels that each got.

#108 Feat/key benefits
  package-lock.json
  package.json
  src/commons/KeyBenefits/Benefit/Body.jsx
  src/commons/KeyBenefits/Benefit/Title.jsx
  src/commons/KeyBenefits/Benefit/index.jsx
  src/commons/KeyBenefits/ControlYourData.jsx
  src/commons/KeyBenefits/ImmediateSettlement.jsx
  src/commons/KeyBenefits/NetworkWithoutBorders.jsx
  src/commons/KeyBenefits/NewBusinessModel.jsx
  src/commons/KeyBenefits/NoFakeReviews.jsx
  src/commons/KeyBenefits/OpenMarketplace.jsx
  src/commons/KeyBenefits/PersonalizedTravel.jsx
  src/commons/KeyBenefits/SetYourCommission.jsx
  src/commons/KeyBenefits/img/1.svg
  src/commons/KeyBenefits/img/2.svg
  src/commons/KeyBenefits/img/3.svg
  src/commons/KeyBenefits/img/4.svg
  src/commons/KeyBenefits/img/5.svg
  src/commons/KeyBenefits/img/6.svg
  src/commons/KeyBenefits/img/7.svg
  src/commons/KeyBenefits/img/8.svg
  src/commons/KeyBenefits/img/9.svg
  src/commons/KeyBenefits/index.jsx
  src/features/Sellers/index.jsx
  src/features/Suppliers/index.jsx
Labels: UI in development, in progress

#110 Roadmap
  _data/roadmap.yml
  _includes/layouts/head.html
  _includes/layouts/scripts.html
  _includes/roadmap.html
  _sass/_bootstrap-custom.scss
  _sass/bootstrap-overrides/_buttons.scss
  _sass/components/_roadmap.scss
  assets/js/components/roadmap.js
Labels: UI in development, in progress

#114 [WIP] feat(card): add card component
  src/commons/Card/index.jsx
Labels: UI in development, in progress

#115 Revert "[WIP] feat(card): add card component"
  src/commons/Card/index.jsx
Labels: UI in development, in progress

#116 feat(Card): add common component card
  package-lock.json
  package.json
  src/commons/Card/index.jsx
Labels: UI in development, in progress

#113 Feat/main/static sections
  README.md
  src/features/Main/DesignedFor.jsx
  src/features/Main/LifToken/index.jsx
  src/features/Main/LifToken/styles.scss
Labels: UI in development, in progress

#117 Feat/lif token view
  package-lock.json
  package.json
  src/commons/KeyBenefits/Lead.jsx
  src/commons/KeyBenefits/PaymentsOnPlatform.jsx
  src/commons/KeyBenefits/PlatformGovernance.jsx
  src/commons/KeyBenefits/index.jsx
  src/features/LifToken/LifIco/Item.jsx
  src/features/LifToken/LifIco/img/1.svg
  src/features/LifToken/LifIco/img/2.svg
  src/features/LifToken/LifIco/img/3.svg
  src/features/LifToken/LifIco/img/4.svg
  src/features/LifToken/LifIco/index.jsx
  src/features/LifToken/index.jsx
Labels: UI in development, in progress

#121 Content
  _data/banners/hacktraveldraft.yml
  _data/banners/winding-tree-hackathon-prague-2018.yml
  _data/events/hacktraveldraft.yml
  _data/events/winding-tree-hackathon-prague-2018.yml
  _sass/components/_terminal.scss
  _sass/components/events/_event.scss
  hacktraveldraft.html
  winding-tree-hackathon-prague-2018(original).html
  winding-tree-hackathon-prague-2018.html
Labels: UI in development, in progress

#123 edited hackathon page
  _data/banners/hacktraveldraft.yml
  _data/events/hacktraveldraft.yml
  _data/events/winding-tree-hackathon-prague-2018.yml
  _includes/banners/winding-tree-hackathon-prague-2018.html
  hacktraveldraft.html
Labels: UI in development, in progress

#125 Feat/update key benefits
  src/commons/KeyBenefits/Benefit/Body.jsx
  src/commons/KeyBenefits/Benefit/Title.jsx
  src/commons/KeyBenefits/Benefit/index.jsx
  src/commons/KeyBenefits/ControlYourData.jsx
  src/commons/KeyBenefits/ImmediateSettlement.jsx
  src/commons/KeyBenefits/NetworkWithoutBorders.jsx
  src/commons/KeyBenefits/NewBusinessModel.jsx
  src/commons/KeyBenefits/NoFakeReviews.jsx
  src/commons/KeyBenefits/OpenMarketplace.jsx
  src/commons/KeyBenefits/PaymentsOnPlatform.jsx
  src/commons/KeyBenefits/PersonalizedTravel.jsx
  src/commons/KeyBenefits/PlatformGovernance.jsx
  src/commons/KeyBenefits/SetYourCommission.jsx
  src/commons/KeyBenefits/index.jsx
  src/features/LifToken/index.jsx
  src/features/LifToken/keyBenefits.json
  src/features/Sellers/index.jsx
  src/features/Sellers/keyBenefits.json
  src/features/Suppliers/index.jsx
  src/features/Suppliers/keyBenefits.json
Labels: UI in development, in progress

#128 Quotes tabs
  src/App/Routes.jsx
  src/App/assets/img/bg-left-with-grid.png
  src/App/assets/img/bg-left.png
  src/App/assets/img/bg-right-with-grid.png
  src/App/assets/img/bg-right.png
  src/App/assets/img/socialbg.png
  src/App/assets/scss/styles.scss
  src/App/index.jsx
  src/features/Home/InThePress/Mentions/data.js
  src/features/Home/InThePress/Mentions/images/Cointelegraph.png
  src/features/Home/InThePress/Mentions/images/Forbes.png
  src/features/Home/InThePress/Mentions/images/Le_Figaro.png
  src/features/Home/InThePress/Mentions/images/VentureBeat.png
  src/features/Home/InThePress/Mentions/images/cash.png
  src/features/Home/InThePress/Mentions/images/ccn.svg
  src/features/Home/InThePress/Mentions/images/financial-times.png
  src/features/Home/InThePress/Mentions/images/investingcom.png
  src/features/Home/InThePress/Mentions/images/nasdaq.png
  src/features/Home/InThePress/Mentions/images/reuters.png
  src/features/Home/InThePress/Mentions/images/spiegel.png
  src/features/Home/InThePress/Mentions/images/tnooz.png
  src/features/Home/InThePress/Mentions/images/tnw.svg
  src/features/Home/InThePress/Mentions/images/yahoofinance.png
  src/features/Home/InThePress/Mentions/index.jsx
  src/features/Home/InThePress/Quotes/data.js
  src/features/Home/InThePress/Quotes/images/airfranceklm.svg
  src/features/Home/InThePress/Quotes/images/businessinsider.png
  src/features/Home/InThePress/Quotes/images/coindesk.png
  src/features/Home/InThePress/Quotes/images/lisa-farrar.jpg
  src/features/Home/InThePress/Quotes/images/skift.svg
  src/features/Home/InThePress/Quotes/index.jsx
  src/features/Home/InThePress/index.jsx
  src/features/Home/index.jsx
Labels: UI in development, in progress

#131 Deploy on pr, merge and release
  .stylelintignore
  .travis.yml
  now-next.json
  now.json
  package-lock.json
  package.json
Labels: frontend in dev, in progress

#122 Feat/contributors slider
  package-lock.json
  package.json
  src/commons/Contributors/DevImage.jsx
  src/commons/Contributors/contributors.js
  src/commons/Contributors/index.jsx
  src/features/StartupsAndDevelopers/index.jsx
Labels: UI, in progress

#138 removed Manuel Aaroz
  _data/advisors.yml
Labels: in progress

#140 Fix mentions section
  package-lock.json
  package.json
  src/features/Home/InThePress/Mentions/data.js
  src/features/Home/InThePress/Mentions/images/ccn.png
  src/features/Home/InThePress/Mentions/images/ccn.svg
Labels: in progress

#139 Feat/partners
  src/features/Home/DesignedFor.jsx
  src/features/Home/LifToken/index.jsx
  src/features/Home/LifToken/styles.scss
  src/features/Home/Partners/Slicks.jsx
  src/features/Home/Partners/data.js
  src/features/Home/Partners/images/Sciant.png
  src/features/Home/Partners/images/air-new-zealand.svg
  src/features/Home/Partners/images/aircanada.png
  src/features/Home/Partners/images/airfranceklm.svg
  src/features/Home/Partners/images/airgateway.jpg
  src/features/Home/Partners/images/austrian.svg
  src/features/Home/Partners/images/basel.png
  src/features/Home/Partners/images/brussels.svg
  src/features/Home/Partners/images/citizen.png
  src/features/Home/Partners/images/erevmax.png
  src/features/Home/Partners/images/eurowings.svg
  src/features/Home/Partners/images/logo-swissport.png
  src/features/Home/Partners/images/lufthansa.svg
  src/features/Home/Partners/images/nordic.png
  src/features/Home/Partners/images/rsk.png
  src/features/Home/Partners/images/siesta.png
  src/features/Home/Partners/images/swiss.svg
  src/features/Home/Partners/images/zeppelin.svg
  src/features/Home/Partners/index.jsx
  src/features/Home/index.jsx
Labels: in progress

#148 Feat/ready to use
  src/App/assets/img/ready-to-use-bg.png
  src/App/assets/scss/styles.scss
  src/commons/Card/index.jsx
  src/commons/LearnMoreCards/data.js
  src/commons/LearnMoreCards/img/1.svg
  src/commons/LearnMoreCards/img/2.svg
  src/commons/LearnMoreCards/img/3.svg
  src/commons/LearnMoreCards/img/4.svg
  src/commons/LearnMoreCards/img/5.svg
  src/commons/LearnMoreCards/index.jsx
  src/commons/ReadyToUse/index.jsx
  src/features/Home/DesignedFor.jsx
  src/features/Home/InThePress/index.jsx
  src/features/Home/LifToken/index.jsx
  src/features/Home/index.jsx
  src/features/Main/index.jsx
Labels: in progress

#149 Feat/features
  src/features/Home/Features/data.js
  src/features/Home/Features/images/1.svg
  src/features/Home/Features/images/2.svg
  src/features/Home/Features/images/3.svg
  src/features/Home/Features/images/4.svg
  src/features/Home/Features/images/5.svg
  src/features/Home/Features/images/6.svg
  src/features/Home/Features/index.jsx
  src/features/Home/index.jsx
Labels: in progress

#154 roadmap updated with desigh and data
  _data/roadmap.yml
  _includes/roadmap.html
  _sass/components/_roadmap.scss
Labels: in progress

#155 travis forcing commit
  foundation.html
Labels: in progress

#156 Feat/video gallery
  package-lock.json
  package.json
  src/commons/VideoGallery/Gallery/Category.jsx
  src/commons/VideoGallery/Gallery/VideoModal.jsx
  src/commons/VideoGallery/Gallery/data.js
  src/commons/VideoGallery/Gallery/images/about.jpg
  src/commons/VideoGallery/Gallery/images/events.jpg
  src/commons/VideoGallery/Gallery/images/partners.jpg
  src/commons/VideoGallery/Gallery/images/tech.jpg
  src/commons/VideoGallery/Gallery/index.jsx
  src/commons/VideoGallery/index.jsx
  src/features/Home/index.jsx
Labels: in progress

#157 Fixed UI issues in homepage sections
  .eslintignore
  .stylelintrc
  package-lock.json
  package.json
  src/commons/Card/index.jsx
  src/commons/HowItWorks/img/HowItWorks.png
  src/commons/HowItWorks/index.jsx
  src/commons/HowItWorks/styles.scss
  src/commons/KeyBenefits/Benefit/index.jsx
  src/commons/KeyBenefits/index.jsx
  src/commons/LearnMoreCards/index.jsx
  src/commons/PartnersAndContributors/index.jsx
  src/commons/ReadyToUse/index.jsx
  src/commons/VideoGallery/Gallery/Category.jsx
  src/commons/VideoGallery/Gallery/index.jsx
  src/commons/VideoGallery/Gallery/styles.css
  src/commons/VideoGallery/Gallery/styles.css.719321853
  src/commons/VideoGallery/index.jsx
  src/features/Home/DesignedFor.jsx
  src/features/Home/Features/index.jsx
  src/features/Home/InThePress/Mentions/index.jsx
  src/features/Home/InThePress/Quotes/index.jsx
  src/features/Home/InThePress/index.jsx
  src/features/Home/LifToken/index.jsx
  src/features/Home/LifToken/styles.scss
  src/features/Home/Partners/Slicks.jsx
  src/features/Home/Partners/index.jsx
  src/features/Home/index.jsx
  src/features/LifToken/LifIco/index.jsx
  src/features/LifToken/index.jsx
  src/features/Main/index.jsx
  src/features/StartupsAndDevelopers/BlockQuoteSection/index.jsx
  src/features/StartupsAndDevelopers/index.jsx
  src/features/Suppliers/Solutions/index.jsx
Labels: in progress

#158 Feat/events
  package.json
  src/commons/Accordion/index.jsx
  src/commons/Events/Event.jsx
  src/commons/Events/EventTab.jsx
  src/commons/Events/EventTabs.jsx
  src/commons/Events/data.js
  src/commons/Events/images/ens.png
  src/commons/Events/index.jsx
  src/features/Home/index.jsx
  src/features/StartupsAndDevelopers/index.jsx
Labels: in progress
